import { Ingredient } from './types';

export const INITIAL_DB: Ingredient[] = [
  {
    "id": "1",
    "name": "Pan Árabe (chato)",
    "unit": 100,
    "carbs": 68.38,
    "protein": 8.66,
    "fatTotal": 3.27,
    "fatSat": 0.195,
    "fatTrans": 0,
    "fiber": 0.27,
    "sodium": 2140,
    "water": 0,
    "at": 1.3,
    "aa": 1.3
  },
  {
    "id": "2",
    "name": "Pan chip",
    "unit": 100,
    "carbs": 53,
    "protein": 7.9,
    "fatTotal": 4.9,
    "fatSat": 0.7,
    "fatTrans": 0.1,
    "fiber": 2.3,
    "sodium": 2140,
    "water": 30.9,
    "at": 0.2,
    "aa": 3.9
  },
  {
    "id": "3",
    "name": "Pan de miga blanco",
    "unit": 100,
    "carbs": 53,
    "protein": 6,
    "fatTotal": 2,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0.1,
    "sodium": 575,
    "water": 33.9,
    "at": 0,
    "aa": 0
  },
  {
    "id": "4",
    "name": "Pan de miga negro",
    "unit": 100,
    "carbs": 50.6,
    "protein": 9,
    "fatTotal": 2.6,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0.5,
    "sodium": 963,
    "water": 34.7,
    "at": 0,
    "aa": 0
  },
  {
    "id": "5",
    "name": "Pan de viena",
    "unit": 100,
    "carbs": 61,
    "protein": 8.1,
    "fatTotal": 4.7,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 2.4,
    "sodium": 437,
    "water": 29.9,
    "at": 0,
    "aa": 0
  },
  {
    "id": "6",
    "name": "Pan lactal Fargo",
    "unit": 100,
    "carbs": 44,
    "protein": 9,
    "fatTotal": 4,
    "fatSat": 0.8,
    "fatTrans": 0,
    "fiber": 4,
    "sodium": 504,
    "water": 37.3,
    "at": 0,
    "aa": 0
  },
  {
    "id": "7",
    "name": "Aceitunas negras Vanoli salm",
    "unit": 100,
    "carbs": 12,
    "protein": 2.2,
    "fatTotal": 19,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 1470,
    "water": 65,
    "at": 0,
    "aa": 0
  },
  {
    "id": "8",
    "name": "Aceitunas verdes Vanoli salmu",
    "unit": 100,
    "carbs": 6,
    "protein": 2,
    "fatTotal": 20,
    "fatSat": 4,
    "fatTrans": 0,
    "fiber": 5,
    "sodium": 1800,
    "water": 70,
    "at": 0,
    "aa": 0
  },
  {
    "id": "9",
    "name": "Ananá al natural",
    "unit": 100,
    "carbs": 16.5,
    "protein": 0,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0.7,
    "sodium": 1,
    "water": 78,
    "at": 0,
    "aa": 0
  },
  {
    "id": "10",
    "name": "Anchoas en aceite",
    "unit": 100,
    "carbs": 0,
    "protein": 12.7,
    "fatTotal": 10,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 80,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "11",
    "name": "Atún al aceite",
    "unit": 100,
    "carbs": 0,
    "protein": 18,
    "fatTotal": 8,
    "fatSat": 2,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 190,
    "water": 53,
    "at": 0,
    "aa": 0
  },
  {
    "id": "12",
    "name": "Bondiola",
    "unit": 100,
    "carbs": 2,
    "protein": 27.5,
    "fatTotal": 17.5,
    "fatSat": 7.5,
    "fatTrans": 0,
    "fiber": 5,
    "sodium": 410,
    "water": 51,
    "at": 0,
    "aa": 0
  },
  {
    "id": "13",
    "name": "Choclo en grano",
    "unit": 100,
    "carbs": 14.8,
    "protein": 1.8,
    "fatTotal": 0.4,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0.6,
    "sodium": 251,
    "water": 82,
    "at": 0,
    "aa": 0
  },
  {
    "id": "14",
    "name": "Crema de leche Sancor",
    "unit": 100,
    "carbs": 2,
    "protein": 2,
    "fatTotal": 40,
    "fatSat": 26,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 47,
    "water": 50,
    "at": 0,
    "aa": 0
  },
  {
    "id": "15",
    "name": "Huevo duro",
    "unit": 100,
    "carbs": 0.4,
    "protein": 12,
    "fatTotal": 11.8,
    "fatSat": 3.18,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 135,
    "water": 74.9,
    "at": 0,
    "aa": 0
  },
  {
    "id": "16",
    "name": "Jamón cocido Lario",
    "unit": 100,
    "carbs": 0,
    "protein": 16.5,
    "fatTotal": 3.5,
    "fatSat": 1.25,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 740,
    "water": 70,
    "at": 0,
    "aa": 0
  },
  {
    "id": "17",
    "name": "Jamón crudo Lario",
    "unit": 100,
    "carbs": 2.75,
    "protein": 24,
    "fatTotal": 23.5,
    "fatSat": 9,
    "fatTrans": 0,
    "fiber": 2.3,
    "sodium": 2952.5,
    "water": 52,
    "at": 0,
    "aa": 0
  },
  {
    "id": "18",
    "name": "Jamón cuadrado cocido",
    "unit": 100,
    "carbs": 0.7,
    "protein": 38.6,
    "fatTotal": 4.2,
    "fatSat": 1.81,
    "fatTrans": 0.21,
    "fiber": 0,
    "sodium": 77,
    "water": 55.3,
    "at": 0,
    "aa": 0
  },
  {
    "id": "19",
    "name": "Lechuga",
    "unit": 100,
    "carbs": 3.5,
    "protein": 1.3,
    "fatTotal": 0.3,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0.7,
    "sodium": 9,
    "water": 94,
    "at": 0,
    "aa": 0
  },
  {
    "id": "20",
    "name": "Manteca Sancor",
    "unit": 100,
    "carbs": 0,
    "protein": 0,
    "fatTotal": 82,
    "fatSat": 53,
    "fatTrans": 3,
    "fiber": 0,
    "sodium": 140,
    "water": 15,
    "at": 0,
    "aa": 0
  },
  {
    "id": "21",
    "name": "Mayonesa Dánica",
    "unit": 100,
    "carbs": 0,
    "protein": 0,
    "fatTotal": 46.68,
    "fatSat": 5.83,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 941.86,
    "water": 13,
    "at": 0,
    "aa": 0
  },
  {
    "id": "22",
    "name": "Medialunas",
    "unit": 100,
    "carbs": 50.35,
    "protein": 9.07,
    "fatTotal": 14.15,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 1.65,
    "sodium": 507,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "23",
    "name": "Morrones Vanoli",
    "unit": 100,
    "carbs": 4.4,
    "protein": 0.6,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0.8,
    "sodium": 159,
    "water": 92,
    "at": 0,
    "aa": 0
  },
  {
    "id": "24",
    "name": "Peceto cocido",
    "unit": 100,
    "carbs": 0,
    "protein": 0,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 0,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "25",
    "name": "Pimienta",
    "unit": 100,
    "carbs": 85,
    "protein": 15,
    "fatTotal": 5,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 5,
    "sodium": 50,
    "water": 15,
    "at": 0,
    "aa": 0
  },
  {
    "id": "26",
    "name": "Pollo cocinado",
    "unit": 100,
    "carbs": 0,
    "protein": 27.3,
    "fatTotal": 13.6,
    "fatSat": 3.79,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 82,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "27",
    "name": "Queso Sardo La Serenisima",
    "unit": 100,
    "carbs": 3.3,
    "protein": 28.3,
    "fatTotal": 30.6,
    "fatSat": 17.3,
    "fatTrans": 1.6,
    "fiber": 0,
    "sodium": 843,
    "water": 36,
    "at": 0,
    "aa": 0
  },
  {
    "id": "28",
    "name": "Queso tybo Masterlac",
    "unit": 100,
    "carbs": 0,
    "protein": 27,
    "fatTotal": 28,
    "fatSat": 15.3,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 956,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "29",
    "name": "Sal",
    "unit": 100,
    "carbs": 0,
    "protein": 0,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 38400,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "30",
    "name": "Queso Reggianito La Serenisima",
    "unit": 100,
    "carbs": 0,
    "protein": 36.6,
    "fatTotal": 25,
    "fatSat": 16,
    "fatTrans": 1,
    "fiber": 0,
    "sodium": 820,
    "water": 33,
    "at": 0,
    "aa": 0
  },
  {
    "id": "31",
    "name": "Salsa golf Dánica",
    "unit": 100,
    "carbs": 13.34,
    "protein": 0,
    "fatTotal": 29.17,
    "fatSat": 4.17,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 866.84,
    "water": 51,
    "at": 0,
    "aa": 0
  },
  {
    "id": "32",
    "name": "Tomate",
    "unit": 100,
    "carbs": 4.7,
    "protein": 1.1,
    "fatTotal": 0.2,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0.5,
    "sodium": 3,
    "water": 94,
    "at": 0,
    "aa": 0
  },
  {
    "id": "33",
    "name": "Vino blanco",
    "unit": 100,
    "carbs": 3.4,
    "protein": 0,
    "fatTotal": 0.2,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 7,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "34",
    "name": "Palmitos",
    "unit": 100,
    "carbs": 8,
    "protein": 2.8,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 1,
    "sodium": 620,
    "water": 89.2,
    "at": 0,
    "aa": 0
  },
  {
    "id": "35",
    "name": "Aceite de girasol",
    "unit": 100,
    "carbs": 0,
    "protein": 0,
    "fatTotal": 99.8,
    "fatSat": 8.6,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 0,
    "water": 0.2,
    "at": 0,
    "aa": 0
  },
  {
    "id": "36",
    "name": "Almendras",
    "unit": 100,
    "carbs": 20.9,
    "protein": 17.7,
    "fatTotal": 54.2,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 3.1,
    "sodium": 0,
    "water": 4,
    "at": 0,
    "aa": 0
  },
  {
    "id": "37",
    "name": "Almíbar",
    "unit": 100,
    "carbs": 0,
    "protein": 0,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 0,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "38",
    "name": "Almidón de maíz",
    "unit": 100,
    "carbs": 88.2,
    "protein": 0.3,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 0,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "39",
    "name": "Azúcar",
    "unit": 100,
    "carbs": 99.5,
    "protein": 0,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 1,
    "water": 0.5,
    "at": 0,
    "aa": 0
  },
  {
    "id": "40",
    "name": "Azúcar impalpable",
    "unit": 100,
    "carbs": 99.5,
    "protein": 0,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 1,
    "water": 0.5,
    "at": 0,
    "aa": 0
  },
  {
    "id": "41",
    "name": "Baño de chocolate",
    "unit": 100,
    "carbs": 0,
    "protein": 0,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 0,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "42",
    "name": "Cacao",
    "unit": 100,
    "carbs": 31,
    "protein": 9,
    "fatTotal": 18.8,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 650,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "43",
    "name": "Caramelo líquido",
    "unit": 100,
    "carbs": 50,
    "protein": 0,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 0,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "44",
    "name": "Castañas de cajú",
    "unit": 100,
    "carbs": 10.9,
    "protein": 14.3,
    "fatTotal": 66.9,
    "fatSat": 0.4,
    "fatTrans": 0,
    "fiber": 2.5,
    "sodium": 12,
    "water": 8,
    "at": 14,
    "aa": 0
  },
  {
    "id": "45",
    "name": "Cerezas en almíbar",
    "unit": 100,
    "carbs": 63.4,
    "protein": 0.21,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0.28,
    "sodium": 0,
    "water": 35,
    "at": 0,
    "aa": 0
  },
  {
    "id": "46",
    "name": "chocolate blanco",
    "unit": 100,
    "carbs": 0,
    "protein": 0,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 0,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "47",
    "name": "Chocolate negro",
    "unit": 100,
    "carbs": 0,
    "protein": 0,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 0,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "48",
    "name": "Claras",
    "unit": 100,
    "carbs": 0.9,
    "protein": 10.9,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 146,
    "water": 88,
    "at": 0,
    "aa": 0
  },
  {
    "id": "49",
    "name": "Coco rallado",
    "unit": 100,
    "carbs": 23,
    "protein": 7.2,
    "fatTotal": 64.9,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 0,
    "water": 4,
    "at": 0,
    "aa": 0
  },
  {
    "id": "50",
    "name": "Cognac",
    "unit": 100,
    "carbs": 0,
    "protein": 0,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 2,
    "water": 65,
    "at": 0,
    "aa": 0
  },
  {
    "id": "51",
    "name": "Crocante de maní",
    "unit": 100,
    "carbs": 0,
    "protein": 0,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 0,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "52",
    "name": "Dulce de leche de repostería",
    "unit": 100,
    "carbs": 57,
    "protein": 6,
    "fatTotal": 6,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 140,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "53",
    "name": "Dulce de membrillo",
    "unit": 100,
    "carbs": 68.45,
    "protein": 0.3,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0.8,
    "sodium": 9,
    "water": 27,
    "at": 0,
    "aa": 0
  },
  {
    "id": "54",
    "name": "Durazno al natural",
    "unit": 100,
    "carbs": 14,
    "protein": 0.92,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 47,
    "water": 80,
    "at": 0,
    "aa": 0
  },
  {
    "id": "55",
    "name": "Extracto de malta",
    "unit": 100,
    "carbs": 0,
    "protein": 0,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 0,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "56",
    "name": "Facturas surt./medialunas",
    "unit": 100,
    "carbs": 50.35,
    "protein": 9.07,
    "fatTotal": 14.15,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0.82,
    "sodium": 253.5,
    "water": 9,
    "at": 0,
    "aa": 0
  },
  {
    "id": "57",
    "name": "Fondant",
    "unit": 100,
    "carbs": 88.8,
    "protein": 0.1,
    "fatTotal": 2,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 114.5,
    "water": 8.5,
    "at": 0,
    "aa": 0
  },
  {
    "id": "58",
    "name": "Fruta abrillantada",
    "unit": 100,
    "carbs": 0,
    "protein": 0,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 0,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "59",
    "name": "Frutillas frescas",
    "unit": 100,
    "carbs": 8.3,
    "protein": 0.8,
    "fatTotal": 0.5,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 1.4,
    "sodium": 0,
    "water": 88.5,
    "at": 0,
    "aa": 0
  },
  {
    "id": "60",
    "name": "Galletitas dulces Lincoln",
    "unit": 100,
    "carbs": 73,
    "protein": 8.2,
    "fatTotal": 13,
    "fatSat": 5.4,
    "fatTrans": 0,
    "fiber": 1.8,
    "sodium": 323,
    "water": 3,
    "at": 0,
    "aa": 0
  },
  {
    "id": "61",
    "name": "Gelatina sin sabor",
    "unit": 100,
    "carbs": 0,
    "protein": 85.6,
    "fatTotal": 0.1,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 0,
    "water": 13,
    "at": 0,
    "aa": 0
  },
  {
    "id": "62",
    "name": "Glucosa",
    "unit": 100,
    "carbs": 0,
    "protein": 0,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 0,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "63",
    "name": "Grasa vacuna",
    "unit": 100,
    "carbs": 0,
    "protein": 0,
    "fatTotal": 99.9,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 0,
    "water": 0.1,
    "at": 0,
    "aa": 0
  },
  {
    "id": "64",
    "name": "Harina",
    "unit": 100,
    "carbs": 72.6,
    "protein": 11,
    "fatTotal": 1.3,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 2,
    "sodium": 3,
    "water": 13.5,
    "at": 0,
    "aa": 0
  },
  {
    "id": "65",
    "name": "Huevos",
    "unit": 100,
    "carbs": 0.4,
    "protein": 12,
    "fatTotal": 11.8,
    "fatSat": 3.18,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 135,
    "water": 74.9,
    "at": 0,
    "aa": 0
  },
  {
    "id": "66",
    "name": "Jalea",
    "unit": 100,
    "carbs": 65,
    "protein": 0.2,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 25,
    "water": 35,
    "at": 0,
    "aa": 0
  },
  {
    "id": "67",
    "name": "Kiwi",
    "unit": 100,
    "carbs": 10.8,
    "protein": 0.8,
    "fatTotal": 0.6,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 2.4,
    "sodium": 4,
    "water": 84,
    "at": 0,
    "aa": 0
  },
  {
    "id": "68",
    "name": "Leche La Paulina semi desc.",
    "unit": 100,
    "carbs": 4.6,
    "protein": 3,
    "fatTotal": 1.5,
    "fatSat": 0.9,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 48,
    "water": 88,
    "at": 0,
    "aa": 0
  },
  {
    "id": "69",
    "name": "Leche La Paulina entera",
    "unit": 100,
    "carbs": 4.7,
    "protein": 3,
    "fatTotal": 3,
    "fatSat": 1.8,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 43,
    "water": 88,
    "at": 0,
    "aa": 0
  },
  {
    "id": "70",
    "name": "Leche condensada",
    "unit": 100,
    "carbs": 58.7,
    "protein": 7.5,
    "fatTotal": 4.1,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 102.4,
    "water": 27,
    "at": 0,
    "aa": 0
  },
  {
    "id": "71",
    "name": "Levadura",
    "unit": 100,
    "carbs": 0,
    "protein": 0,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 0,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "72",
    "name": "Limón",
    "unit": 100,
    "carbs": 8.1,
    "protein": 0.6,
    "fatTotal": 0.6,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0.6,
    "sodium": 1,
    "water": 90,
    "at": 0,
    "aa": 0
  },
  {
    "id": "73",
    "name": "Malta",
    "unit": 100,
    "carbs": 11.5,
    "protein": 0.6,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 0,
    "water": 86.5,
    "at": 0,
    "aa": 0
  },
  {
    "id": "74",
    "name": "Maní",
    "unit": 100,
    "carbs": 6,
    "protein": 28.1,
    "fatTotal": 48.5,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 0,
    "water": 10,
    "at": 0,
    "aa": 0
  },
  {
    "id": "75",
    "name": "Manzanas",
    "unit": 100,
    "carbs": 14.5,
    "protein": 0.2,
    "fatTotal": 0.6,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 1,
    "sodium": 1,
    "water": 84,
    "at": 0,
    "aa": 0
  },
  {
    "id": "76",
    "name": "Margarina Margadán",
    "unit": 100,
    "carbs": 0,
    "protein": 0,
    "fatTotal": 74,
    "fatSat": 20,
    "fatTrans": 25,
    "fiber": 0,
    "sodium": 270,
    "water": 18,
    "at": 0,
    "aa": 0
  },
  {
    "id": "77",
    "name": "Mermelada de frutillas Orieta",
    "unit": 100,
    "carbs": 80.4,
    "protein": 1.68,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 1.38,
    "sodium": 9.7,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "78",
    "name": "Mermelada de membrillo Orieta",
    "unit": 100,
    "carbs": 70,
    "protein": 0.5,
    "fatTotal": 0.05,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 40,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "79",
    "name": "Miel",
    "unit": 100,
    "carbs": 75.1,
    "protein": 0.3,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 7,
    "water": 19,
    "at": 0,
    "aa": 0
  },
  {
    "id": "80",
    "name": "Naranjas",
    "unit": 100,
    "carbs": 12.2,
    "protein": 1,
    "fatTotal": 0.2,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0.5,
    "sodium": 1,
    "water": 86,
    "at": 0,
    "aa": 0
  },
  {
    "id": "81",
    "name": "Nueces",
    "unit": 100,
    "carbs": 14.3,
    "protein": 16.2,
    "fatTotal": 63.85,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 1.05,
    "sodium": 1.5,
    "water": 1.65,
    "at": 0,
    "aa": 0
  },
  {
    "id": "82",
    "name": "Pasas de uva",
    "unit": 100,
    "carbs": 62.2,
    "protein": 2.1,
    "fatTotal": 0.5,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 3.8,
    "sodium": 21,
    "water": 16,
    "at": 0,
    "aa": 0
  },
  {
    "id": "83",
    "name": "Pasta para cubrir tortas",
    "unit": 100,
    "carbs": 0,
    "protein": 0,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 0,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "84",
    "name": "Pionono",
    "unit": 100,
    "carbs": 0,
    "protein": 0,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 0,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "85",
    "name": "Polvo para hornear",
    "unit": 100,
    "carbs": 0,
    "protein": 0,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 0,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "86",
    "name": "Pulpa de frutillas",
    "unit": 100,
    "carbs": 24.5,
    "protein": 0.4,
    "fatTotal": 0.1,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 2.3,
    "sodium": 0,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "87",
    "name": "Queso crema casancrem",
    "unit": 100,
    "carbs": 3.2,
    "protein": 7,
    "fatTotal": 19,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 0,
    "water": 65,
    "at": 0,
    "aa": 0
  },
  {
    "id": "88",
    "name": "Ralladura de limón",
    "unit": 100,
    "carbs": 0,
    "protein": 0,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 0,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "89",
    "name": "Pickles Vanoli",
    "unit": 100,
    "carbs": 3.5,
    "protein": 0.8,
    "fatTotal": 2,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 1.1,
    "sodium": 1030,
    "water": 90,
    "at": 0,
    "aa": 0
  },
  {
    "id": "90",
    "name": "Ricota la Serenísima",
    "unit": 100,
    "carbs": 4,
    "protein": 10,
    "fatTotal": 17,
    "fatSat": 12,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 130,
    "water": 65,
    "at": 0,
    "aa": 0
  },
  {
    "id": "91",
    "name": "Salvado de trigo",
    "unit": 100,
    "carbs": 61.9,
    "protein": 16,
    "fatTotal": 4.6,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 9.1,
    "sodium": 9,
    "water": 12,
    "at": 0,
    "aa": 0
  },
  {
    "id": "92",
    "name": "Uvas negras",
    "unit": 100,
    "carbs": 20.5,
    "protein": 0.5,
    "fatTotal": 0.5,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0.4,
    "sodium": 0,
    "water": 78,
    "at": 0,
    "aa": 0
  },
  {
    "id": "93",
    "name": "V ermouth Americano 14% alc",
    "unit": 100,
    "carbs": 0,
    "protein": 0,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 0,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "94",
    "name": "Pimienta negra",
    "unit": 100,
    "carbs": 66.75,
    "protein": 9.2,
    "fatTotal": 6.5,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 12.3,
    "sodium": 35,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "95",
    "name": "Perejil",
    "unit": 100,
    "carbs": 8.5,
    "protein": 3.2,
    "fatTotal": 0.6,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 1.3,
    "sodium": 28,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "96",
    "name": "Ajo",
    "unit": 100,
    "carbs": 29.3,
    "protein": 5.3,
    "fatTotal": 0.2,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 1.1,
    "sodium": 6,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "97",
    "name": "Acelga hervida",
    "unit": 100,
    "carbs": 2.8,
    "protein": 2.6,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 74,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "98",
    "name": "Ajï rojo-amarilli-verde",
    "unit": 100,
    "carbs": 5,
    "protein": 0.85,
    "fatTotal": 0.15,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 1.1,
    "sodium": 0,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "99",
    "name": "Ají cocido",
    "unit": 100,
    "carbs": 6.75,
    "protein": 1.21,
    "fatTotal": 0.2,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 1.48,
    "sodium": 0,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "100",
    "name": "Morrones envasados",
    "unit": 100,
    "carbs": 5.8,
    "protein": 0.9,
    "fatTotal": 0.5,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0.6,
    "sodium": 0,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "101",
    "name": "Zanahoria cruda",
    "unit": 100,
    "carbs": 9.7,
    "protein": 1.1,
    "fatTotal": 0.2,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 1,
    "sodium": 47,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "102",
    "name": "Matambre de cerdo /carne semi.coci",
    "unit": 100,
    "carbs": 0,
    "protein": 23.57,
    "fatTotal": 40,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 0,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "103",
    "name": "Tapita de cuadril/vacío crudo",
    "unit": 100,
    "carbs": 0,
    "protein": 23.8,
    "fatTotal": 8.4,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 70,
    "water": 61,
    "at": 2,
    "aa": 0
  },
  {
    "id": "104",
    "name": "Peceto/Nalga cocido",
    "unit": 100,
    "carbs": 0.6,
    "protein": 35.1,
    "fatTotal": 3.8,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 71,
    "water": 60,
    "at": 0,
    "aa": 0
  },
  {
    "id": "105",
    "name": "Panceta Ahumada",
    "unit": 100,
    "carbs": 0,
    "protein": 13,
    "fatTotal": 49,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 1170,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "106",
    "name": "Pollo Hervido",
    "unit": 100,
    "carbs": 0,
    "protein": 27.3,
    "fatTotal": 13.6,
    "fatSat": 3.79,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 82,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "107",
    "name": "Pechuga de pollo cruda",
    "unit": 100,
    "carbs": 0,
    "protein": 20.8,
    "fatTotal": 2.4,
    "fatSat": 0.76,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 72,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "108",
    "name": "Pechuga de pollo cocida",
    "unit": 100,
    "carbs": 1,
    "protein": 28.6,
    "fatTotal": 3.2,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 110,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "109",
    "name": "Lengua de vaca cruda",
    "unit": 100,
    "carbs": 0.4,
    "protein": 15.8,
    "fatTotal": 16.3,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 56,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "110",
    "name": "Papa hervida",
    "unit": 100,
    "carbs": 19.6,
    "protein": 2.4,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 17,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "111",
    "name": "Zanahoria cocida",
    "unit": 100,
    "carbs": 0,
    "protein": 0,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 0,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "112",
    "name": "Tapita de cuadri/vacío cocido",
    "unit": 100,
    "carbs": 0,
    "protein": 28.1,
    "fatTotal": 14.3,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 63,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "113",
    "name": "Peceto/Nalga crudo",
    "unit": 100,
    "carbs": 2.5,
    "protein": 21,
    "fatTotal": 1.1,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 0,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "114",
    "name": "Cebolla blanca cocida",
    "unit": 100,
    "carbs": 1.8,
    "protein": 0.6,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 26,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "115",
    "name": "Zapallo cocido",
    "unit": 100,
    "carbs": 4.6,
    "protein": 0.4,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 4,
    "water": 94,
    "at": 0,
    "aa": 0
  },
  {
    "id": "116",
    "name": "Calamares crudo",
    "unit": 100,
    "carbs": 0,
    "protein": 18.4,
    "fatTotal": 0.9,
    "fatSat": 0.2,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 500,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "117",
    "name": "Calamares cocidos",
    "unit": 100,
    "carbs": 0,
    "protein": 30.54,
    "fatTotal": 1.49,
    "fatSat": 0.33,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 830,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "118",
    "name": "Arvejas en lata",
    "unit": 100,
    "carbs": 13.1,
    "protein": 1.77,
    "fatTotal": 0.31,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 1.4,
    "sodium": 288.5,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "119",
    "name": "Pan rallado",
    "unit": 100,
    "carbs": 57.4,
    "protein": 9.3,
    "fatTotal": 0.2,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0.2,
    "sodium": 274,
    "water": 31,
    "at": 0,
    "aa": 0
  },
  {
    "id": "120",
    "name": "Perejil deshidratado",
    "unit": 100,
    "carbs": 23.7,
    "protein": 0.4,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0.4,
    "sodium": 0,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "121",
    "name": "Provenzal deshidratado",
    "unit": 100,
    "carbs": 39,
    "protein": 2.6,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0.6,
    "sodium": 0,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "122",
    "name": "pre - pizza Miño",
    "unit": 100,
    "carbs": 53.25,
    "protein": 9.25,
    "fatTotal": 7,
    "fatSat": 3,
    "fatTrans": 0,
    "fiber": 3,
    "sodium": 800,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "123",
    "name": "Queso Muzzrella Masterlac",
    "unit": 100,
    "carbs": 0,
    "protein": 26.6,
    "fatTotal": 26.6,
    "fatSat": 14.3,
    "fatTrans": 1.3,
    "fiber": 0,
    "sodium": 516,
    "water": 0,
    "at": 0,
    "aa": 0
  },
  {
    "id": "124",
    "name": "Rucula",
    "unit": 100,
    "carbs": 3.7,
    "protein": 2.6,
    "fatTotal": 0.7,
    "fatSat": 0.09,
    "fatTrans": 0,
    "fiber": 1.6,
    "sodium": 27,
    "water": 0,
    "at": 2.1,
    "aa": 0
  },
  {
    "id": "125",
    "name": "lechuga",
    "unit": 100,
    "carbs": 2.8,
    "protein": 1.2,
    "fatTotal": 0.2,
    "fatSat": 0.03,
    "fatTrans": 0,
    "fiber": 1.4,
    "sodium": 13,
    "water": 79,
    "at": 1.2,
    "aa": 0
  },
  {
    "id": "126",
    "name": "huevo duro",
    "unit": 100,
    "carbs": 55.4,
    "protein": 6.61,
    "fatTotal": 16,
    "fatSat": 4.1,
    "fatTrans": 4.75,
    "fiber": 0.94,
    "sodium": 68.6,
    "water": 20,
    "at": 0,
    "aa": 0
  },
  {
    "id": "127",
    "name": "Tomate desecado",
    "unit": 100,
    "carbs": 55.76,
    "protein": 14.1,
    "fatTotal": 2.97,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 12.3,
    "sodium": 600,
    "water": 24,
    "at": 0,
    "aa": 0
  },
  {
    "id": "128",
    "name": "Masa",
    "unit": 100,
    "carbs": 57,
    "protein": 9.7,
    "fatTotal": 6.6,
    "fatSat": 1,
    "fatTrans": 0,
    "fiber": 1,
    "sodium": 177,
    "water": 22,
    "at": 0,
    "aa": 0
  },
  {
    "id": "129",
    "name": "Azafran",
    "unit": 100,
    "carbs": 61.5,
    "protein": 11.43,
    "fatTotal": 5.8,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 1,
    "sodium": 148,
    "water": 18,
    "at": 0,
    "aa": 0
  },
  {
    "id": "130",
    "name": "Agua",
    "unit": 100,
    "carbs": 0,
    "protein": 0,
    "fatTotal": 0,
    "fatSat": 0,
    "fatTrans": 0,
    "fiber": 0,
    "sodium": 0,
    "water": 0,
    "at": 0,
    "aa": 0
  }
];

export const DAILY_VALUES = {
  carbs: 300,
  at: 50,
  aa: 50,
  protein: 75,
  fatTotal: 55,
  fatSat: 22,
  fiber: 25,
  sodium: 2400,
};
